# Generated by Django 3.2.25 on 2026-04-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bale_id',
            new_name='user_id',
        ),
    ]
