# Generated by Django 3.2.25 on 2026-04-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_bale_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
    ]
